### ISSUE TITLE
[Next 15] upgrade error: Unable to render chart using Next.JS App routing

### ISSUE THREAD

**Issue by dajevu** [palerdot/react-d3-speedometer#189] opened 2024-11-14 15:16 UTC
While I was able to create graph components and display when using page routing, when I move the page to app routing, I keep getting the error:

`node_modules\react-d3-speedometer\dist\react-d3-speedometer.es.js (19:1936) @ eval
 ⨯ TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at (rsc)/./node_modules/react-d3-speedometer/dist/react-d3-speedometer.es.js (C:\Users\jeffd\Documents\github\my-speedometer-app\.next\server\vendor-chunks\react-d3-speedometer.js:20:1)`

I tried also putting the ""use client" directive in the app page, but to no avail. Once I move under pages, it renders fine. Probably I'm doing something wrong on my end, but I exhausted everything I could think of.

Thanks!

jeff

**Comment by palerdot** [comment] 2024-11-14 17:00
Can you share a link to stackblitz/codesandbox where you can reproduce this issue? It is difficult to debug without a reproducible repo. Most likely it might have to do with server components for page.tsx/layout.tsx and you might have to wrap your component with `use client`. Not sure if this was done right.

**Comment by dajevu** [comment] 2024-11-14 18:05
Sure, let me get that spun up. 

Here's the component I created (app/components/Speedometer.js):

```
"use client";
import dynamic from 'next/dynamic';
const ReactSpeedometer = dynamic(() => import('react-d3-speedometer'), { ssr: false });

const Speedometer = () => (
  <div style={{ width: '300px', height: '200px' }}>
    <ReactSpeedometer
      maxValue={100}
      value={70}
      needleColor="red"
      startColor="green"
      segments={10}
      endColor="blue"
      textColor="black"
    />
  </div>
);
```

export default Speedometer;

And here is my app/page.js:

```
"use client";
import Speedometer from './components/Speedometer';

export default function Home() {
  return (
    <div>
      <h1>Speedometer Example</h1>
      <Speedometer />
    </div>
  );
}
```

(I also tried omitting the "use client" directive on the page).

I'm pretty certain it's something on my end - somewhat of a newbie at this stuff and am very grateful for the help.

jeff

**Comment by palerdot** [comment] 2024-11-14 18:11
> Note: v2.x is compatible with React v18. v1.x is compatible with React 17. Please use latest v0.x (v0.14.1 at the time of writing) if you are using React 16.

**Comment by dajevu** [comment] 2024-11-14 19:24
Here's the package.json

```
{
  "name": "my-speedometer-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "my-speedometer-app": "file:",
    "next": "latest",
    "react": "^18",
    "react-d3-speedometer": "^2.2.1",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "typescript": "^5"
  }
}

```

I think it would be most helpful to get a codestandbox instance setup - I'll get that done (just hadn't used it previously so wasn't certain of the effort required).

**Comment by dajevu** [comment] 2024-11-15 03:28
I created the app in codesandbox, but not entirely sure how to make it public. However, I did send you an invite to the app - https://hxy6s5-3000.csb.app/.

I put the code in the "not-working" branch. If you want, feel free to make any changes/updates, as it's currently a public github repo - https://github.com/dajevu/att-speedometer-app

I'm very appreciative of any help you can offer.

**Comment by palerdot** [comment] 2024-11-15 03:38
Ok. I will take a look and revert back here if I'm able to spot the issue

**Comment by palerdot** [comment] 2024-11-15 07:14
This looks like a Next 15 upgrade error. There are other instances like this out in the wild, for example - https://github.com/calcom/cal.com/issues/16656. I don't have immediate solutions. I will keep this open till I stumble upon some solution for `Next 15`.

**Comment by palerdot** [comment] 2024-11-21 17:46
@KlotzJesse I will look into your suggestion. But, `react` is correctly marked as external right? I'm just surprised what makes just Next 15 to break and how `/^react\/.*/` fixes the issue for `Next 15`

**Comment by KlotzJesse** [comment] 2024-11-21 23:23
@palerdot Seems like not, we had the same for react-email, which had also a bigger bundle size (would optimize it), you can verify it by finding `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner` in the dist, see:
https://unpkg.com//react-d3-speedometer/dist/react-d3-speedometer.es.js

**Comment by palerdot** [comment] 2024-11-22 06:24
Thanks for the suggestion. I will look into this and mark this change for the next major version for `React 19`.

**Closed** 2024-11-23 04:07 UTC

**Comment by palerdot** [comment] 2024-11-23 07:39
`v3.0.0-rc.0` is released - https://github.com/palerdot/react-d3-speedometer/issues/191

Please install this version if you are using Next 15. Please reopen if you still face issues.
