### ISSUE TITLE
Unexpected identifier "baseGetTag "

### ISSUE THREAD

**Issue by laitanop** [palerdot/react-d3-speedometer#72] opened 2020-04-08 17:31 UTC
I installed with "yarn" when I import ReactSpeedometer, it shows this error.

<img width="1362" alt="Captura de Pantalla 2020-04-08 a la(s) 11 23 19" src="https://user-images.githubusercontent.com/21044809/78814142-6deec100-798b-11ea-8c79-5557cb1aab26.png">

**Comment by palerdot** [comment] 2020-04-09 08:07
can you share a reproducible code sandbox or something?

**Comment by palerdot** [comment] 2020-04-09 08:08
@laitanop  or maybe something like a reproducible repo where I can check this issue ... thanks ...

**Comment by palerdot** [comment] 2020-04-09 08:33
Here is a codesandbox link where it works fine - https://codesandbox.io/s/stoic-hooks-rjcvu?file=/src/App.js

**Comment by palerdot** [comment] 2020-04-09 08:42
My guess is that your build system does not understand `es6` identifiers like `import/export` ... , Almost all of the react app templates, for eg: with `[create-react-app](https://github.com/facebook/create-react-app)` will support this out of the box ... I can share an example repo created with `create-react-app` where things are working

**Comment by palerdot** [comment] 2020-04-09 08:47
> My guess is that your build system does not understand `es6` identifiers like `import/export` ... , Almost all of the react app templates, for eg: with `[create-react-app](https://github.com/facebook/create-react-app)` will support this out of the box ... I can share an example repo created with `create-react-app` where things are working

@laitanop To verify this, you can downgrade to `0.10.x` and see if it works fine. Because in `v0.11.0`, the library moved to [lodash-es](https://www.npmjs.com/package/lodash-es) from `lodash` as former provides tree shaking resulting in smaller bundle sizes in your final app bundle. You can see the [CHANGELOG](https://github.com/palerdot/react-d3-speedometer/blob/master/CHANGELOG.md#0110) for more details. If that is the case, you might want to upgrade your app bundling to support `es6` code imports ...

**Comment by palerdot** [comment] 2020-04-10 15:26
I'm closing this issue since this seems like a problem around the bundling setup of the project, and not the library itself. Please reopen if you find issues with the library itself.

**Closed by palerdot** 2020-04-10 15:26 UTC

**Comment by jamneck** [comment] 2020-04-18 20:54
> I'm closing this issue since this seems like a problem around the bundling setup of the project, and not the library itself. Please reopen if you find issues with the library itself.

I encountered the same issue on a project started with `create-next-app`. Downgrading to `0.10.x` resolved the issue.

Thanks for the good work.

**Comment by palerdot** [comment] 2020-04-20 04:48
ok ... Alternatively you can use `babel` to make your bundling process understand `es6` modules out of the box, so that you can keep using libraries like `lodash-es` that export `es6` modules ...
